spring:
  application:
    name: auweather
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: NMZWWfABZJXU3gMwbRTWbhPxk5E1FDhP
            client-secret: V0M8P8Ym3SN7-AOQ3WQ73f_aN4PIZOakHFArJ3AKNNVFA7l1ccA4SrZBsoPXWVE6
            scope: openid+profile+email
        provider:
          auth0:
            issuer-uri: https://dev-mcw7dlhmns8chw5m.us.auth0.com/

logging.level.root: ERROR
logging.level.org.springframework.web: ERROR
logging.level.org.wealther.demo: ERROR

open.weather.url: https://api.openweathermap.org/data/2.5/forecast
open.weather.apikey: 5f86cadd4448649434232b96050a3f7d

resilience4j:
  circuitbreaker:
    instances:
      weather-map:
        sliding-window-type: COUNT_BASED
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        register-health-indicator: true

