spring:
  application:
    name: auweather
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: [TBF]
            client-secret: [TBF]
            scope: openid+profile+email
        provider:
          auth0:
            issuer-uri: [TBF]

logging.level.root: ERROR
logging.level.org.springframework.web: ERROR
logging.level.org.wealther.demo: ERROR

open.weather.url: https://api.openweathermap.org/data/2.5/forecast
open.weather.apikey: [FB]

resilience4j:
  circuitbreaker:
    instances:
      weather-map:
        sliding-window-type: COUNT_BASED
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        register-health-indicator: true

